language: csharp
solution: AkamaiEdgeGrid.sln
mono: none
dotnet: 2.0.3
script:
  - dotnet build
before_script:
  - dotnet restore
after_script:
  - cd EdgeGrid-Signer-httpclient-unit-tests
  - dotnet test